version: '3'

services:

  dash-backend:
    build: .
    image: dashboard:latest
    volumes:
      - /tmp/:/tmp_host/
    ports:
    - 8080

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.size=500MB'
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter:latest
    ports:
    - 9100

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./configs/grafana/datasource/all.yml:/etc/grafana/provisioning/datasources/all.yml
      - ./configs/grafana/dashboards/dash-config.yml:/etc/grafana/provisioning/dashboards/dash-config.yml
      - ./configs/grafana/dashboards/boards:/var/lib/grafana/dashboards
    ports:
    - 3000:3000

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000


