global:
  scrape_interval: 10s

scrape_configs:
- job_name: 'spring_micrometer'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 60s
  static_configs:
  - targets: ['dash-backend:8080']
- job_name: 'node_exporter'
  metrics_path: '//metrics'
  scrape_interval: 60s
  static_configs:
  - targets: ['node-exporter:9100']
